# Generated by Django 4.1.5 on 2023-08-04 20:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Idioma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idioma', models.CharField(max_length=70)),
                ('descripcion', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pais', models.CharField(max_length=70)),
                ('descripcion', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roles', models.CharField(max_length=45)),
                ('descripcion', models.CharField(max_length=85)),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rfc', models.CharField(max_length=13, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=10, null=True)),
                ('cedulaprofesional', models.CharField(max_length=8, unique=True)),
                ('jefeproyectos', models.BooleanField()),
                ('Idioma', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Scrum.idioma')),
                ('Pais', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Scrum.pais')),
                ('Usuario', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuarioempleado', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
