# Generated by Django 4.1.5 on 2023-08-07 18:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Scrum', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstatusHistoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estatus', models.CharField(max_length=100)),
                ('descripcion', models.CharField(blank=True, max_length=300, null=True)),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='EstatusSprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estatus', models.CharField(max_length=100)),
                ('descripcion', models.CharField(blank=True, max_length=300, null=True)),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='EstatusTarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estatus', models.CharField(max_length=100)),
                ('descripcion', models.CharField(blank=True, max_length=300, null=True)),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='HistoriaUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('fechacreacion', models.DateField(blank=True)),
                ('ultimaactualizacion', models.DateField(blank=True)),
                ('descripcion', models.CharField(max_length=1000)),
                ('Estatus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='EstatusHistoriasUsuarios', to='Scrum.estatushistoria')),
            ],
        ),
        migrations.CreateModel(
            name='JefeProyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rfc', models.CharField(max_length=13, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=10, null=True)),
                ('cedulaprofesional', models.CharField(max_length=8, unique=True)),
                ('Idioma', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Scrum.idioma')),
                ('Pais', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Scrum.pais')),
                ('Usuario', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuariojefeproyecto', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreproyecto', models.CharField(max_length=200, unique=True)),
                ('fechainicio', models.DateField(blank=True)),
                ('fechafinal', models.DateField(blank=True)),
                ('objetivo', models.CharField(blank=True, max_length=1000, null=True)),
                ('impacto', models.CharField(blank=True, max_length=1000, null=True)),
                ('homologacionvision', models.CharField(blank=True, max_length=1000, null=True)),
                ('JefeProyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='JefeProyectoProyectos', to='Scrum.jefeproyecto')),
            ],
        ),
        migrations.CreateModel(
            name='Sprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombresprint', models.CharField(max_length=200)),
                ('fechainiciosprint', models.DateField()),
                ('fechafinalsprint', models.DateField(blank=True, null=True)),
                ('numerosprint', models.IntegerField()),
                ('objetivosprint', models.CharField(max_length=400)),
                ('Estatus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='EstatusSprints', to='Scrum.estatussprint')),
                ('Proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ProyectoSprints', to='Scrum.proyecto')),
            ],
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='jefeproyectos',
        ),
        migrations.AddField(
            model_name='empleado',
            name='Roles',
            field=models.ManyToManyField(to='Scrum.rol'),
        ),
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechainicioplaneado', models.DateField(blank=True)),
                ('fechainicioreal', models.DateField(blank=True, null=True)),
                ('fechafinalplaneado', models.DateField(blank=True)),
                ('fechafinalreal', models.DateField(blank=True, null=True)),
                ('horasestimadas', models.IntegerField()),
                ('horasreales', models.IntegerField(null=True)),
                ('Estatus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='EstatusHistorias', to='Scrum.estatushistoria')),
                ('HistoriaUsuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='HistoriaTareas', to='Scrum.historiausuario')),
                ('Rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='RolTareas', to='Scrum.rol')),
            ],
        ),
        migrations.CreateModel(
            name='SprintBacklog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observaciones', models.CharField(blank=True, max_length=1000, null=True)),
                ('Empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='EmpleadoSprintBacklog', to='Scrum.empleado')),
                ('Sprint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SprintSprintBacklogs', to='Scrum.sprint')),
                ('Tarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='TareaSprintBacklogs', to='Scrum.tarea')),
            ],
        ),
        migrations.CreateModel(
            name='ReunionDiaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('observaciones', models.CharField(blank=True, max_length=1000, null=True)),
                ('Sprint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SprintReuniones', to='Scrum.sprint')),
            ],
        ),
        migrations.CreateModel(
            name='Progreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horasinvertivas', models.IntegerField()),
                ('ReunionDiaria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ReuniondiariaProgresos', to='Scrum.reuniondiaria')),
                ('SprintBacklog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SprintBacklogProgresos', to='Scrum.sprintbacklog')),
            ],
        ),
        migrations.CreateModel(
            name='ProductBacklog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaelavoracio', models.DateField(blank=True)),
                ('ultimaactualizacion', models.DateField(blank=True)),
                ('Proyecto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Scrum.proyecto')),
            ],
        ),
        migrations.AddField(
            model_name='historiausuario',
            name='ProductBacklog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='BacklogHistorias', to='Scrum.productbacklog'),
        ),
        migrations.CreateModel(
            name='EmpleadoProyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Empleado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='DetalleEmpleado', to='Scrum.empleado')),
                ('Proyecto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='DetalleProyecto', to='Scrum.proyecto')),
            ],
        ),
    ]
