# Generated by Django 4.1.5 on 2023-08-07 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Scrum', '0002_estatushistoria_estatussprint_estatustarea_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='Estatus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='EstatusTareas', to='Scrum.estatustarea'),
        ),
    ]
