# Generated by Django 4.1.5 on 2023-08-17 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Scrum', '0004_alter_empleado_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productbacklog',
            old_name='fechaelavoracio',
            new_name='fechaelavoracion',
        ),
    ]
