# Generated by Django 4.1.5 on 2023-08-17 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scrum', '0006_alter_productbacklog_fechaelavoracion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productbacklog',
            name='fechaelavoracion',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='productbacklog',
            name='ultimaactualizacion',
            field=models.DateField(null=True),
        ),
    ]
