# Generated by Django 4.1.5 on 2023-08-17 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Scrum', '0008_alter_historiausuario_productbacklog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historiausuario',
            name='ProductBacklog',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='BacklogHistorias', to='Scrum.productbacklog'),
            preserve_default=False,
        ),
    ]
