# Generated by Django 4.1.5 on 2023-08-17 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scrum', '0009_alter_historiausuario_productbacklog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historiausuario',
            name='ultimaactualizacion',
            field=models.DateField(blank=True, null=True),
        ),
    ]
