# Generated by Django 4.1.5 on 2023-08-25 00:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Scrum', '0010_alter_historiausuario_ultimaactualizacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='historiausuario',
            name='Sprint',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='SprintHistoriasUsuario', to='Scrum.sprint'),
        ),
        migrations.AlterField(
            model_name='historiausuario',
            name='fechacreacion',
            field=models.DateField(),
        ),
    ]
