# Generated by Django 4.1.5 on 2023-09-05 00:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Scrum', '0011_historiausuario_sprint_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sprintbacklog',
            name='Empleado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='EmpleadoSprintBacklog', to='Scrum.empleado'),
        ),
    ]
