# Generated by Django 4.1.5 on 2023-09-07 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scrum', '0012_alter_sprintbacklog_empleado'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reuniondiaria',
            options={'ordering': ['fecha']},
        ),
        migrations.RemoveField(
            model_name='sprintbacklog',
            name='Sprint',
        ),
        migrations.AlterField(
            model_name='sprintbacklog',
            name='observaciones',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
