# Generated by Django 4.1.5 on 2023-09-07 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Scrum', '0013_alter_reuniondiaria_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarea',
            name='horasreales',
        ),
    ]
