# Generated by Django 4.1.5 on 2023-09-11 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Scrum', '0015_prioridadtarea'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prioridadtarea',
            options={'ordering': ['pk']},
        ),
        migrations.AddField(
            model_name='tarea',
            name='Prioridad',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='PrioridadTareas', to='Scrum.prioridadtarea'),
            preserve_default=False,
        ),
    ]
