# Generated by Django 4.1.5 on 2023-09-21 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scrum', '0017_sprintbacklog_sprint'),
    ]

    operations = [
        migrations.AddField(
            model_name='historiausuario',
            name='tereas_asignadas',
            field=models.BooleanField(null=True),
        ),
    ]
