# Generated by Django 4.1.5 on 2023-09-22 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Scrum', '0019_remove_historiausuario_tereas_asignadas_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prioridadtarea',
            old_name='color',
            new_name='colors',
        ),
    ]
