# Generated by Django 4.1.5 on 2023-09-22 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scrum', '0020_rename_color_prioridadtarea_colors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prioridadtarea',
            name='colors',
            field=models.CharField(max_length=100),
        ),
    ]
