# Generated by Django 4.1.5 on 2024-02-26 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Mensajes', '0001_initial'),
        ('Scrum', '0023_eventoscrum_mensaje_alter_historiausuario_idmensaje'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mensaje',
            name='Emisor',
        ),
        migrations.RemoveField(
            model_name='mensaje',
            name='EventoScrum',
        ),
        migrations.RemoveField(
            model_name='mensaje',
            name='Proyecto',
        ),
        migrations.RemoveField(
            model_name='historiausuario',
            name='IdMensaje',
        ),
        migrations.AddField(
            model_name='historiausuario',
            name='Mensaje',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Mensajes.mensaje'),
        ),
        migrations.AlterField(
            model_name='historiausuario',
            name='CriteriosAceptacion',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='historiausuario',
            name='HorasEstimadas',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historiausuario',
            name='Prioridad',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='EventoScrum',
        ),
        migrations.DeleteModel(
            name='Mensaje',
        ),
    ]
