# Generated by Django 4.1.5 on 2024-02-26 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Scrum', '0024_remove_mensaje_emisor_remove_mensaje_eventoscrum_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rol',
            old_name='roles',
            new_name='NombreRol',
        ),
        migrations.RemoveField(
            model_name='rol',
            name='descripcion',
        ),
    ]
