# Generated by Django 4.1.5 on 2024-02-28 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Scrum', '0025_rename_roles_rol_nombrerol_remove_rol_descripcion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historiausuario',
            old_name='Mensaje',
            new_name='MensajeRPBL',
        ),
    ]
