# Generated by Django 4.1.5 on 2024-02-28 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Scrum', '0026_rename_mensaje_historiausuario_mensajerpbl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historiausuario',
            name='Sprint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='SprintHistoriasUsuario', to='Scrum.sprint'),
        ),
    ]
