# Generated by Django 4.1.5 on 2024-03-14 04:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Scrum', '0027_alter_historiausuario_sprint'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleado',
            name='Roles',
        ),
        migrations.AddField(
            model_name='empleado',
            name='Roles',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='Scrum.rol'),
        ),
    ]
