# Generated by Django 4.1.5 on 2024-04-07 22:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Scrum', '0028_remove_empleado_roles_empleado_roles'),
    ]

    operations = [
        migrations.CreateModel(
            name='tareaAsignada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarea', models.CharField(max_length=50)),
                ('horasEstimadas', models.IntegerField()),
                ('developer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tareaHistoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Scrum.historiausuario')),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
    ]
