# Generated by Django 4.1.5 on 2024-05-01 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Scrum', '0029_tareaasignada'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tareaAsignada',
        ),
    ]
