# Generated by Django 4.1.5 on 2024-05-02 03:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Scrum', '0030_delete_tareaasignada'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='Empleado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Scrum.empleado'),
        ),
    ]
