# Generated by Django 4.1.5 on 2024-05-14 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scrum', '0034_alter_historiausuario_prioridad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historiausuario',
            name='Prioridad',
            field=models.CharField(blank=True, choices=[('1', 'Alta'), ('2', 'Media'), ('3', 'Baja')], max_length=1, null=True),
        ),
    ]
