# Generated by Django 4.1.5 on 2024-05-20 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Scrum', '0035_alter_historiausuario_prioridad'),
    ]

    operations = [
        migrations.CreateModel(
            name='TareaAvance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaAvance', models.DateField(auto_now=True)),
                ('horasDedicadas', models.IntegerField()),
                ('horasRestantes', models.IntegerField(blank=True, null=True)),
                ('HistoriaUsuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='HistoriaTareasAvance', to='Scrum.historiausuario', unique=True)),
                ('tarea', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tareaAvance', to='Scrum.tarea', unique=True)),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
    ]
