# Generated by Django 4.1.5 on 2024-05-20 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Scrum', '0036_tareaavance'),
    ]

    operations = [
        migrations.CreateModel(
            name='sprint_Backlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Scrum.proyecto')),
                ('Sprint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Scrum.sprint')),
                ('historiaUsuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Scrum.historiausuario')),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
    ]
