# Generated by Django 5.0.6 on 2024-06-10 23:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scrum', '0037_sprint_backlog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historiausuario',
            name='ProductBacklog',
        ),
        migrations.AddField(
            model_name='historiausuario',
            name='Proyecto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ProyectoHistoriasUsuario', to='Scrum.proyecto'),
        ),
        migrations.AddField(
            model_name='tarea',
            name='Proyecto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ProyectoTareas', to='Scrum.proyecto'),
        ),
    ]
