# Generated by Django 5.0.6 on 2024-06-12 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Scrum', '0040_rename_proyecto_id_historiausuario_proyecto_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductBacklog',
        ),
    ]
