# Generated by Django 5.0.6 on 2024-06-12 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Scrum', '0041_delete_productbacklog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historiausuario',
            old_name='Proyecto',
            new_name='Proyecto_id',
        ),
        migrations.RenameField(
            model_name='tarea',
            old_name='Proyecto',
            new_name='Proyecto_id',
        ),
    ]
