# Generated by Django 5.0.6 on 2024-06-12 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Scrum', '0042_rename_proyecto_historiausuario_proyecto_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historiausuario',
            old_name='Proyecto_id',
            new_name='Proyecto',
        ),
    ]
