# Generated by Django 5.0.6 on 2024-06-12 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Scrum', '0043_rename_proyecto_id_historiausuario_proyecto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tarea',
            old_name='Proyecto_id',
            new_name='Proyecto',
        ),
    ]
