# Generated by Django 5.0.6 on 2024-07-08 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scrum', '0046_tareaavance_horasreales'),
    ]

    operations = [
        migrations.AddField(
            model_name='tareaavance',
            name='semanas',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
