# Generated by Django 5.0.6 on 2024-07-08 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scrum', '0047_tareaavance_semanas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tareaavance',
            name='semanas',
            field=models.JSONField(default=dict),
        ),
    ]
