# Generated by Django 5.0.6 on 2024-07-08 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scrum', '0048_alter_tareaavance_semanas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tareaavance',
            name='semanas',
        ),
        migrations.CreateModel(
            name='HorasRealesPorSemana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semana_numero', models.IntegerField()),
                ('horas_reales', models.CharField(default='0/0', max_length=5)),
                ('tarea_avance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horas_reales_por_semana', to='Scrum.tareaavance')),
            ],
            options={
                'unique_together': {('tarea_avance', 'semana_numero')},
            },
        ),
    ]
