# Generated by Django 5.0.6 on 2024-07-08 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scrum', '0049_remove_tareaavance_semanas_horasrealesporsemana'),
    ]

    operations = [
        migrations.AddField(
            model_name='tareaavance',
            name='semana_1',
            field=models.CharField(blank=True, default='0/0', max_length=5),
        ),
        migrations.AddField(
            model_name='tareaavance',
            name='semana_2',
            field=models.CharField(blank=True, default='0/0', max_length=5),
        ),
        migrations.AddField(
            model_name='tareaavance',
            name='semana_3',
            field=models.CharField(blank=True, default='0/0', max_length=5),
        ),
        migrations.AddField(
            model_name='tareaavance',
            name='semana_4',
            field=models.CharField(blank=True, default='0/0', max_length=5),
        ),
        migrations.AddField(
            model_name='tareaavance',
            name='semana_5',
            field=models.CharField(blank=True, default='0/0', max_length=5),
        ),
        migrations.DeleteModel(
            name='HorasRealesPorSemana',
        ),
    ]
