# Generated by Django 5.0.6 on 2024-07-19 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scrum', '0052_remove_tareaavance_dia_1_remove_tareaavance_dia_10_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tareaavance',
            options={},
        ),
        migrations.AddField(
            model_name='tareaavance',
            name='dia_1',
            field=models.CharField(blank=True, default='0/0', max_length=5),
        ),
        migrations.AddField(
            model_name='tareaavance',
            name='dia_10',
            field=models.CharField(blank=True, default='0/0', max_length=5),
        ),
        migrations.AddField(
            model_name='tareaavance',
            name='dia_11',
            field=models.CharField(blank=True, default='0/0', max_length=5),
        ),
        migrations.AddField(
            model_name='tareaavance',
            name='dia_12',
            field=models.CharField(blank=True, default='0/0', max_length=5),
        ),
        migrations.AddField(
            model_name='tareaavance',
            name='dia_13',
            field=models.CharField(blank=True, default='0/0', max_length=5),
        ),
        migrations.AddField(
            model_name='tareaavance',
            name='dia_14',
            field=models.CharField(blank=True, default='0/0', max_length=5),
        ),
        migrations.AddField(
            model_name='tareaavance',
            name='dia_15',
            field=models.CharField(blank=True, default='0/0', max_length=5),
        ),
        migrations.AddField(
            model_name='tareaavance',
            name='dia_16',
            field=models.CharField(blank=True, default='0/0', max_length=5),
        ),
        migrations.AddField(
            model_name='tareaavance',
            name='dia_17',
            field=models.CharField(blank=True, default='0/0', max_length=5),
        ),
        migrations.AddField(
            model_name='tareaavance',
            name='dia_18',
            field=models.CharField(blank=True, default='0/0', max_length=5),
        ),
        migrations.AddField(
            model_name='tareaavance',
            name='dia_19',
            field=models.CharField(blank=True, default='0/0', max_length=5),
        ),
        migrations.AddField(
            model_name='tareaavance',
            name='dia_2',
            field=models.CharField(blank=True, default='0/0', max_length=5),
        ),
        migrations.AddField(
            model_name='tareaavance',
            name='dia_20',
            field=models.CharField(blank=True, default='0/0', max_length=5),
        ),
        migrations.AddField(
            model_name='tareaavance',
            name='dia_21',
            field=models.CharField(blank=True, default='0/0', max_length=5),
        ),
        migrations.AddField(
            model_name='tareaavance',
            name='dia_22',
            field=models.CharField(blank=True, default='0/0', max_length=5),
        ),
        migrations.AddField(
            model_name='tareaavance',
            name='dia_23',
            field=models.CharField(blank=True, default='0/0', max_length=5),
        ),
        migrations.AddField(
            model_name='tareaavance',
            name='dia_24',
            field=models.CharField(blank=True, default='0/0', max_length=5),
        ),
        migrations.AddField(
            model_name='tareaavance',
            name='dia_25',
            field=models.CharField(blank=True, default='0/0', max_length=5),
        ),
        migrations.AddField(
            model_name='tareaavance',
            name='dia_26',
            field=models.CharField(blank=True, default='0/0', max_length=5),
        ),
        migrations.AddField(
            model_name='tareaavance',
            name='dia_27',
            field=models.CharField(blank=True, default='0/0', max_length=5),
        ),
        migrations.AddField(
            model_name='tareaavance',
            name='dia_28',
            field=models.CharField(blank=True, default='0/0', max_length=5),
        ),
        migrations.AddField(
            model_name='tareaavance',
            name='dia_29',
            field=models.CharField(blank=True, default='0/0', max_length=5),
        ),
        migrations.AddField(
            model_name='tareaavance',
            name='dia_3',
            field=models.CharField(blank=True, default='0/0', max_length=5),
        ),
        migrations.AddField(
            model_name='tareaavance',
            name='dia_30',
            field=models.CharField(blank=True, default='0/0', max_length=5),
        ),
        migrations.AddField(
            model_name='tareaavance',
            name='dia_31',
            field=models.CharField(blank=True, default='0/0', max_length=5),
        ),
        migrations.AddField(
            model_name='tareaavance',
            name='dia_4',
            field=models.CharField(blank=True, default='0/0', max_length=5),
        ),
        migrations.AddField(
            model_name='tareaavance',
            name='dia_5',
            field=models.CharField(blank=True, default='0/0', max_length=5),
        ),
        migrations.AddField(
            model_name='tareaavance',
            name='dia_6',
            field=models.CharField(blank=True, default='0/0', max_length=5),
        ),
        migrations.AddField(
            model_name='tareaavance',
            name='dia_7',
            field=models.CharField(blank=True, default='0/0', max_length=5),
        ),
        migrations.AddField(
            model_name='tareaavance',
            name='dia_8',
            field=models.CharField(blank=True, default='0/0', max_length=5),
        ),
        migrations.AddField(
            model_name='tareaavance',
            name='dia_9',
            field=models.CharField(blank=True, default='0/0', max_length=5),
        ),
    ]
