# Generated by Django 5.0.6 on 2024-08-06 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scrum', '0054_tareas_kanban'),
    ]

    operations = [
        migrations.AddField(
            model_name='tareas_kanban',
            name='horasRestantes',
            field=models.FloatField(default=0),
        ),
    ]
