# Generated by Django 5.0.6 on 2024-08-06 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scrum', '0055_tareas_kanban_horasrestantes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tareas_kanban',
            name='horasRestantes',
            field=models.IntegerField(default=0),
        ),
    ]
