# Generated by Django 5.0.6 on 2024-08-14 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scrum', '0056_alter_tareas_kanban_horasrestantes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarea',
            name='Empleado',
        ),
        migrations.AddField(
            model_name='tarea',
            name='Empleado',
            field=models.ManyToManyField(blank=True, to='Scrum.empleado'),
        ),
    ]
