# Generated by Django 5.0.6 on 2024-08-14 22:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scrum', '0057_remove_tarea_empleado_tarea_empleado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarea',
            name='Empleado',
        ),
        migrations.AddField(
            model_name='tarea',
            name='Empleado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Scrum.empleado'),
        ),
    ]
