# Generated by Django 5.0.6 on 2024-08-14 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scrum', '0058_remove_tarea_empleado_tarea_empleado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='fechafinalplaneado',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='fechainicioplaneado',
            field=models.DateField(blank=True, null=True),
        ),
    ]
