# Generated by Django 4.1.5 on 2024-08-25 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Scrum', '0063_alter_tareaavance_dia_31'),
    ]

    operations = [
    ]
