# Generated by Django 4.1.5 on 2024-09-05 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scrum', '0064_auto_20240825_0121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historiausuario',
            name='CriteriosAceptacion',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
