# Generated by Django 4.2.7 on 2024-10-03 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scrum', '0065_alter_historiausuario_criteriosaceptacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='historiausuario',
            name='NumeroHU',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
