# Generated by Django 4.2.7 on 2024-10-23 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scrum', '0067_alter_tareaavance_fechaavance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historiausuario',
            name='CriteriosAceptacion',
            field=models.CharField(blank=True, max_length=1200, null=True),
        ),
    ]
