# Generated by Django 4.2.7 on 2024-10-23 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scrum', '0068_alter_historiausuario_criteriosaceptacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historiausuario',
            name='CriteriosAceptacion',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
