# Generated by Django 4.2.7 on 2024-10-30 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scrum', '0069_alter_historiausuario_criteriosaceptacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='historiausuario',
            name='HUAceptada',
            field=models.CharField(blank=True, choices=[('1', 'Si'), ('2', 'No')], max_length=1, null=True),
        ),
    ]
