# Generated by Django 4.2.7 on 2024-11-18 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Scrum', '0073_empresa_numero_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='Empresa',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Empresa_Proyecto', to='Scrum.empresa'),
        ),
    ]
