# Generated by Django 4.2.7 on 2025-04-10 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scrum', '0075_tareaavance_horasrestantescaptura'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleadoproyecto',
            name='Status',
            field=models.CharField(blank=True, choices=[('0', 'Baja'), ('1', 'Activo')], max_length=1, null=True),
        ),
    ]
