# Generated by Django 4.1.5 on 2024-02-26 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Scrum', '0025_rename_roles_rol_nombrerol_remove_rol_descripcion'),
        ('Mensajes', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EventoScrum',
            new_name='m_EventoScrum',
        ),
        migrations.CreateModel(
            name='m_RefinamientoProductBL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FechaHora', models.DateTimeField(blank=True)),
                ('Emisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Scrum.empleado')),
                ('Mensaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Mensajes.mensaje')),
                ('Proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Scrum.proyecto')),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='m_ConfiguracionMensaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IdRolReceptor', models.IntegerField(blank=True, null=True)),
                ('EventoScrum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Mensajes.m_eventoscrum')),
                ('Proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Scrum.proyecto')),
                ('RolEmisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Scrum.rol')),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='AsistentesEventosScrum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fecha', models.DateField(blank=True)),
                ('Status', models.IntegerField(blank=True, null=True)),
                ('EventoScrum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Mensajes.m_eventoscrum')),
                ('Proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Scrum.proyecto')),
                ('Rol', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Scrum.rol')),
                ('Usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Scrum.empleado')),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
    ]
