# Generated by Django 4.1.5 on 2024-02-26 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mensajes', '0002_rename_eventoscrum_m_eventoscrum_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asistenteseventosscrum',
            name='TipoAsistencia',
            field=models.CharField(choices=[('S', 'Síncrona'), ('A', 'Asíncrona')], default='S', max_length=1),
        ),
    ]
