# Generated by Django 4.1.5 on 2024-02-26 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Mensajes', '0003_asistenteseventosscrum_tipoasistencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='asistenteseventosscrum',
            name='Mensaje',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Mensajes.mensaje'),
        ),
        migrations.AlterField(
            model_name='asistenteseventosscrum',
            name='Status',
            field=models.CharField(choices=[('1', 'Obligatorio'), ('2', 'Opcional')], default='1', max_length=1),
        ),
    ]
