# Generated by Django 4.1.5 on 2024-02-26 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mensajes', '0004_asistenteseventosscrum_mensaje_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='m_eventoscrum',
            name='Descripcion',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
