# Generated by Django 4.1.5 on 2024-02-27 06:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Scrum', '0025_rename_roles_rol_nombrerol_remove_rol_descripcion'),
        ('Mensajes', '0005_alter_m_eventoscrum_descripcion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='m_configuracionmensaje',
            name='IdRolReceptor',
        ),
        migrations.AddField(
            model_name='m_configuracionmensaje',
            name='RolReceptor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='RolReceptor', to='Scrum.rol'),
        ),
        migrations.AlterField(
            model_name='m_configuracionmensaje',
            name='RolEmisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='RolEmisor', to='Scrum.rol'),
        ),
    ]
