# Generated by Django 4.1.5 on 2024-02-28 05:43

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Scrum', '0026_rename_mensaje_historiausuario_mensajerpbl'),
        ('Mensajes', '0006_remove_m_configuracionmensaje_idrolreceptor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensaje',
            name='FHCreacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mensaje',
            name='FHUltimaMod',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mensaje',
            name='Status',
            field=models.CharField(choices=[('1', 'Generado'), ('2', 'Enviado'), ('3', 'Comprendido'), ('4', 'Cancelado')], default='1', max_length=1),
        ),
        migrations.CreateModel(
            name='MensajeRetroA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Descripcion', models.CharField(blank=True, max_length=400, null=True)),
                ('Contestacion', models.CharField(blank=True, max_length=400, null=True)),
                ('FHCreacion', models.DateTimeField(auto_now_add=True)),
                ('FHUltimaMod', models.DateTimeField(auto_now_add=True)),
                ('Status', models.CharField(choices=[('1', 'Generado'), ('2', 'Enviado'), ('3', 'Aclarado y/o Comprendido'), ('4', 'Cancelado')], default='1', max_length=1)),
                ('Emisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Scrum.empleado')),
                ('EventoScrum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Mensajes.m_eventoscrum')),
                ('Mensaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Mensajes.mensaje')),
                ('Proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Scrum.proyecto')),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='MensajeReceptor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FHCreacion', models.DateTimeField(auto_now_add=True)),
                ('FHUltimaMod', models.DateTimeField(auto_now_add=True)),
                ('Status', models.CharField(choices=[('1', 'Recibido'), ('2', 'Comprendido'), ('3', 'NO Comprendido')], default='1', max_length=1)),
                ('Mensaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Mensajes.mensaje')),
                ('Proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Scrum.proyecto')),
                ('Receptor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Scrum.empleado')),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
    ]
