# Generated by Django 4.1.5 on 2024-02-28 17:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Mensajes', '0007_mensaje_fhcreacion_mensaje_fhultimamod_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asistenteseventosscrum',
            name='Fecha',
        ),
        migrations.AddField(
            model_name='asistenteseventosscrum',
            name='FechaHora',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
