# Generated by Django 4.1.5 on 2024-02-28 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Mensajes', '0008_remove_asistenteseventosscrum_fecha_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mensaje',
            old_name='FHCreacion',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='mensaje',
            old_name='FHUltimaMod',
            new_name='updated',
        ),
    ]
