# Generated by Django 4.1.5 on 2024-02-28 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mensajes', '0009_rename_fhcreacion_mensaje_created_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mensaje',
            old_name='created',
            new_name='FHCreacion',
        ),
        migrations.RemoveField(
            model_name='mensaje',
            name='updated',
        ),
        migrations.AddField(
            model_name='mensaje',
            name='FHUltimaMod',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='asistenteseventosscrum',
            name='FechaHora',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='mensajereceptor',
            name='FHUltimaMod',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='mensajeretroa',
            name='FHUltimaMod',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
