# Generated by Django 4.1.5 on 2024-03-15 05:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Scrum', '0028_remove_empleado_roles_empleado_roles'),
        ('Mensajes', '0010_rename_created_mensaje_fhcreacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensaje',
            name='Emisor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='MensajeEmisor', to='Scrum.empleado'),
        ),
    ]
