# Generated by Django 4.1.5 on 2024-03-15 05:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Mensajes', '0011_alter_mensaje_emisor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensaje',
            name='Emisor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='MensajeEmisor', to=settings.AUTH_USER_MODEL),
        ),
    ]
