# Generated by Django 4.1.5 on 2024-03-15 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mensajes', '0013_alter_m_refinamientoproductbl_emisor'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensaje',
            name='FechaHora',
            field=models.DateTimeField(null=True),
        ),
    ]
