# Generated by Django 4.1.5 on 2024-03-15 22:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Mensajes', '0015_alter_mensaje_eventoscrum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistenteseventosscrum',
            name='EventoScrum',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Mensajes.m_eventoscrum'),
        ),
    ]
