# Generated by Django 4.1.5 on 2024-03-15 22:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Scrum', '0028_remove_empleado_roles_empleado_roles'),
        ('Mensajes', '0016_alter_asistenteseventosscrum_eventoscrum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistenteseventosscrum',
            name='Proyecto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Scrum.proyecto'),
        ),
    ]
