# Generated by Django 4.1.5 on 2024-03-16 04:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Mensajes', '0018_alter_asistenteseventosscrum_eventoscrum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistenteseventosscrum',
            name='EventoScrum',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Mensajes.m_eventoscrum'),
        ),
    ]
