# Generated by Django 4.1.5 on 2024-03-17 22:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Mensajes', '0019_alter_asistenteseventosscrum_eventoscrum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistenteseventosscrum',
            name='Usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
