# Generated by Django 4.1.5 on 2024-03-17 22:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Mensajes', '0020_alter_asistenteseventosscrum_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensaje',
            name='EventoScrum',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='Mensajes.m_eventoscrum'),
        ),
    ]
