# Generated by Django 4.1.5 on 2024-03-20 05:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Scrum', '0028_remove_empleado_roles_empleado_roles'),
        ('Mensajes', '0022_mensaje_destinatario'),
    ]

    operations = [
        migrations.CreateModel(
            name='m_Archivos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Descripcion', models.CharField(max_length=100)),
                ('Archivo', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('Mensaje', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Mensajes.mensaje')),
                ('Proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Scrum.proyecto')),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
    ]
