# Generated by Django 4.1.5 on 2024-03-20 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Scrum', '0028_remove_empleado_roles_empleado_roles'),
        ('Mensajes', '0023_m_archivos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='m_archivos',
            name='Archivo',
            field=models.FileField(upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='m_archivos',
            name='Proyecto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Scrum.proyecto'),
        ),
    ]
