# Generated by Django 4.1.5 on 2024-03-20 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mensajes', '0024_alter_m_archivos_archivo_alter_m_archivos_proyecto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='m_archivos',
            name='Archivo',
            field=models.FileField(null=True, upload_to='documents/'),
        ),
    ]
