# Generated by Django 4.1.5 on 2024-03-20 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mensajes', '0025_alter_m_archivos_archivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='m_archivos',
            name='Archivo',
            field=models.FileField(upload_to='documents/'),
        ),
    ]
