# Generated by Django 4.1.5 on 2024-03-21 04:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Scrum', '0028_remove_empleado_roles_empleado_roles'),
        ('Mensajes', '0027_mensaje_archivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensajeretroa',
            name='Receptor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='retroReceptor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mensajeretroa',
            name='Emisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='retroEmisor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mensajeretroa',
            name='EventoScrum',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Mensajes.m_eventoscrum'),
        ),
        migrations.AlterField(
            model_name='mensajeretroa',
            name='Mensaje',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Mensajes.mensaje'),
        ),
        migrations.AlterField(
            model_name='mensajeretroa',
            name='Proyecto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Scrum.proyecto'),
        ),
    ]
