# Generated by Django 4.1.5 on 2024-03-21 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mensajes', '0028_mensajeretroa_receptor_alter_mensajeretroa_emisor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensajeretroa',
            name='Contestacion',
            field=models.CharField(max_length=400),
        ),
    ]
