# Generated by Django 4.1.5 on 2024-03-22 04:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Mensajes', '0029_alter_mensajeretroa_contestacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensajereceptor',
            name='Receptor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
