# Generated by Django 4.1.5 on 2024-03-22 04:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Mensajes', '0030_alter_mensajereceptor_receptor'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensajereceptor',
            name='archivo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Mensajes.m_archivos'),
        ),
    ]
