# Generated by Django 4.1.5 on 2024-03-24 22:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Scrum', '0028_remove_empleado_roles_empleado_roles'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Mensajes', '0031_mensajereceptor_archivo'),
    ]

    operations = [
        migrations.CreateModel(
            name='m_ReunionDiaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FechaHora', models.DateTimeField()),
                ('ObstaculosPresentados', models.CharField(max_length=100)),
                ('PlanDiaSiguiente', models.CharField(max_length=100)),
                ('TrabajoRealizadoDiaAnterior', models.CharField(max_length=100)),
                ('Emisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('Mensaje', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Mensajes.mensaje')),
                ('Proyecto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Scrum.proyecto')),
                ('Sprint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Scrum.sprint')),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
    ]
