# Generated by Django 4.1.5 on 2024-03-24 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mensajes', '0032_m_reuniondiaria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='m_reuniondiaria',
            name='ObstaculosPresentados',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='m_reuniondiaria',
            name='PlanDiaSiguiente',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='m_reuniondiaria',
            name='TrabajoRealizadoDiaAnterior',
            field=models.CharField(max_length=500),
        ),
    ]
