# Generated by Django 4.1.5 on 2024-03-26 22:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Scrum', '0028_remove_empleado_roles_empleado_roles'),
        ('Mensajes', '0036_alter_mensaje_destinatario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensajeretroa',
            name='Emisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='retroEmisor', to='Scrum.empleado'),
        ),
        migrations.CreateModel(
            name='m_RetrospectivaSprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Comentarios', models.CharField(max_length=200)),
                ('FechaHora', models.DateTimeField()),
                ('OportunidadesMejora', models.CharField(max_length=200)),
                ('Emisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Scrum.empleado')),
                ('Mensaje', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Mensajes.mensaje')),
                ('Proyecto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Scrum.proyecto')),
                ('Sprint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Scrum.sprint')),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='m_PlanificacionSprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FechaHora', models.DateTimeField()),
                ('Emisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Scrum.empleado')),
                ('Mensaje', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Mensajes.mensaje')),
                ('Proyecto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Scrum.proyecto')),
                ('Sprint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Scrum.sprint')),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='m_HomologacionVision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FechaHora', models.DateTimeField()),
                ('Emisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Scrum.empleado')),
                ('Mensaje', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Mensajes.mensaje')),
                ('Proyecto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Scrum.proyecto')),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='m_CierreSprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FechaHora', models.DateTimeField(auto_now=True)),
                ('Emisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Scrum.empleado')),
                ('Mensaje', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Mensajes.mensaje')),
                ('Proyecto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Scrum.proyecto')),
                ('Sprint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Scrum.sprint')),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
    ]
