# Generated by Django 4.1.5 on 2024-04-09 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mensajes', '0037_alter_mensajeretroa_emisor_m_retrospectivasprint_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensajeretroa',
            name='Contestacion',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='mensajeretroa',
            name='Descripcion',
            field=models.CharField(max_length=400),
        ),
    ]
