# Generated by Django 4.1.5 on 2024-04-11 03:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Scrum', '0029_tareaasignada'),
        ('Mensajes', '0038_alter_mensajeretroa_contestacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='m_refinamientoproductbl',
            name='Emisor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Scrum.empleado'),
        ),
        migrations.AlterField(
            model_name='mensaje',
            name='Emisor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='MensajeEmisor', to='Scrum.empleado'),
        ),
        migrations.AlterField(
            model_name='mensajereceptor',
            name='Receptor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Scrum.empleado'),
        ),
        migrations.AlterField(
            model_name='mensajeretroa',
            name='Receptor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='retroReceptor', to='Scrum.empleado'),
        ),
    ]
