# Generated by Django 4.1.5 on 2024-04-12 03:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Scrum', '0029_tareaasignada'),
        ('Mensajes', '0039_alter_m_refinamientoproductbl_emisor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensajereceptor',
            name='Descripcion',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='mensajereceptor',
            name='Emisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receptorEmisor', to='Scrum.empleado'),
        ),
        migrations.AddField(
            model_name='mensajereceptor',
            name='EventoScrum',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Mensajes.m_eventoscrum'),
        ),
    ]
