# Generated by Django 4.1.5 on 2024-04-14 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Mensajes', '0040_mensajereceptor_descripcion_mensajereceptor_emisor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mensajereceptor',
            name='Descripcion',
        ),
    ]
