# Generated by Django 4.1.5 on 2024-04-22 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Scrum', '0029_tareaasignada'),
        ('Mensajes', '0041_remove_mensajereceptor_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensaje',
            name='Sprint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Scrum.sprint'),
        ),
        migrations.AlterField(
            model_name='mensajeretroa',
            name='Status',
            field=models.CharField(choices=[('1', 'Generado'), ('2', 'Enviado'), ('3', 'Aclarado y/o Comprendido'), ('4', 'Cancelado'), ('5', 'No Comprendido')], default='1', max_length=1),
        ),
    ]
