# Generated by Django 4.1.5 on 2024-04-26 04:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Scrum', '0029_tareaasignada'),
        ('Mensajes', '0042_mensaje_sprint_alter_mensajeretroa_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensajereceptor',
            name='Sprint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Scrum.sprint'),
        ),
    ]
