# Generated by Django 4.1.5 on 2024-04-28 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Mensajes', '0044_remove_mensaje_destinatario'),
    ]

    operations = [
        migrations.CreateModel(
            name='m_Comentarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Comentarios', models.CharField(max_length=200)),
                ('Mensaje', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Mensajes.mensaje')),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
    ]
