# Generated by Django 4.1.5 on 2024-04-28 22:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Scrum', '0029_tareaasignada'),
        ('Mensajes', '0045_m_comentarios'),
    ]

    operations = [
        migrations.AddField(
            model_name='m_comentarios',
            name='Emisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Scrum.empleado'),
        ),
        migrations.AddField(
            model_name='m_comentarios',
            name='EventoScrum',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Mensajes.m_eventoscrum'),
        ),
    ]
