# Generated by Django 4.1.5 on 2024-05-05 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mensajes', '0046_m_comentarios_emisor_m_comentarios_eventoscrum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='m_cierresprint',
            name='FechaHora',
            field=models.DateTimeField(),
        ),
    ]
