# Generated by Django 4.1.5 on 2024-05-12 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mensajes', '0047_alter_m_cierresprint_fechahora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='m_retrospectivasprint',
            name='FechaHora',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
