# Generated by Django 4.1.5 on 2024-05-15 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Mensajes', '0048_alter_m_retrospectivasprint_fechahora'),
    ]

    operations = [
        migrations.DeleteModel(
            name='m_ReunionDiaria',
        ),
    ]
