# Generated by Django 4.1.5 on 2024-05-27 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Mensajes', '0050_m_reuniondiaria'),
    ]

    operations = [
        migrations.CreateModel(
            name='dia_sprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.DateTimeField()),
                ('horasDedicadas', models.IntegerField()),
                ('sprint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Mensajes.mensaje')),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
    ]
