# Generated by Django 4.1.5 on 2024-08-25 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Mensajes', '0052_alter_dia_sprint_sprint'),
    ]

    operations = [
    ]
