# Generated by Django 4.2.7 on 2025-06-11 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mensajes', '0055_alter_m_comentarios_comentarios_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mensaje',
            name='archivo',
        ),
        migrations.AddField(
            model_name='mensaje',
            name='ArchivosGenerados',
            field=models.BooleanField(default=False),
        ),
    ]
