# Generated by Django 4.2.7 on 2025-06-11 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Mensajes', '0056_remove_mensaje_archivo_mensaje_archivosgenerados'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mensajereceptor',
            name='archivo',
        ),
    ]
